# OpenAPI Specification for Isaac Robot Brain Educational Module
# This represents how the educational content could be programmatically accessed

openapi: 3.0.0
info:
  title: Isaac Robot Brain Educational Module API
  description: API for accessing educational content about NVIDIA Isaac for humanoid robots
  version: 1.0.0

paths:
  /chapters:
    get:
      summary: List all available chapters
      description: Returns a list of all chapters in the Isaac Robot Brain module
      responses:
        '200':
          description: List of chapters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chapter'

  /chapters/{chapterId}:
    get:
      summary: Get specific chapter content
      description: Returns the content of a specific chapter
      parameters:
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
            enum: [isaac-sim-fundamentals, isaac-ros-perception-vslam, navigation-with-nav2-humanoids]
          description: ID of the chapter to retrieve
      responses:
        '200':
          description: Chapter content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChapterContent'

  /concepts:
    get:
      summary: List all key concepts
      description: Returns a list of all key concepts covered in the module
      responses:
        '200':
          description: List of concepts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Concept'

components:
  schemas:
    Chapter:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the chapter
        title:
          type: string
          description: Title of the chapter
        description:
          type: string
          description: Brief description of the chapter
        learningObjectives:
          type: array
          items:
            type: string
          description: List of learning objectives for the chapter
        duration:
          type: string
          description: Estimated time to complete the chapter

    ChapterContent:
      type: object
      properties:
        chapter:
          $ref: '#/components/schemas/Chapter'
        content:
          type: string
          description: Markdown content of the chapter
        keyTerms:
          type: array
          items:
            type: string
          description: Important terms defined in the chapter
        examples:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              description:
                type: string

    Concept:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the concept
        name:
          type: string
          description: Name of the concept
        definition:
          type: string
          description: Definition of the concept
        relatedChapters:
          type: array
          items:
            type: string
          description: Chapters where this concept is covered
        examples:
          type: array
          items:
            type: string
          description: Examples of the concept in practice